package com.networkdiagnostics

import android.content.Context
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.util.Log
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.WritableMap

/**
 * TurboModule implementation. The abstract base class
 * [NativeNetworkDiagnosticsSpec] is generated by React Native Codegen from
 * src/NativeNetworkDiagnostics.ts.
 *
 * Threading:
 * - getNetworkState performs a quick binder call on the native-modules thread.
 * - probeEndpoint is asynchronous on OkHttp's dispatcher threads.
 * - Monitoring callbacks arrive on ConnectivityManager's callback thread.
 * Nothing here runs on, or blocks, the UI thread.
 */
class NetworkDiagnosticsModule(reactContext: ReactApplicationContext) :
  NativeNetworkDiagnosticsSpec(reactContext) {

  private val inspector by lazy { NetworkInspector(reactContext) }
  private val prober by lazy { EndpointProber() }

  private val monitorLock = Any()
  private var networkCallback: ConnectivityManager.NetworkCallback? = null
  private var lastEmitted: NetworkStateResult? = null

  override fun getNetworkState(promise: Promise) {
    try {
      if (!inspector.isAvailable) {
        promise.reject(
          ProbeErrorMapper.DIAGNOSTIC_UNAVAILABLE,
          "ConnectivityManager is not available on this device"
        )
        return
      }
      promise.resolve(stateToMap(inspector.currentState()))
    } catch (e: SecurityException) {
      promise.reject(
        ProbeErrorMapper.DIAGNOSTIC_UNAVAILABLE,
        "Missing permission android.permission.ACCESS_NETWORK_STATE",
        e
      )
    } catch (e: RuntimeException) {
      promise.reject(ProbeErrorMapper.UNKNOWN, ProbeErrorMapper.messageFor(e), e)
    }
  }

  override fun probeEndpoint(url: String, method: String, timeoutMs: Double, promise: Promise) {
    val timeout = timeoutMs.toLong().coerceIn(MIN_TIMEOUT_MS, MAX_TIMEOUT_MS)
    try {
      prober.probe(url, method, timeout) { outcome ->
        promise.resolve(outcomeToMap(outcome))
      }
    } catch (e: RuntimeException) {
      // Never reject for network conditions; report them as data.
      promise.resolve(
        outcomeToMap(
          ProbeOutcome(
            responded = false,
            errorCode = ProbeErrorMapper.codeFor(e),
            errorMessage = ProbeErrorMapper.messageFor(e),
          )
        )
      )
    }
  }

  override fun startMonitoring() {
    synchronized(monitorLock) {
      if (networkCallback != null) return
      val cm = reactApplicationContext.getSystemService(Context.CONNECTIVITY_SERVICE)
        as? ConnectivityManager ?: return
      val callback = object : ConnectivityManager.NetworkCallback() {
        override fun onAvailable(network: Network) {
          emitIfChanged(inspector.currentState())
        }

        override fun onCapabilitiesChanged(network: Network, capabilities: NetworkCapabilities) {
          emitIfChanged(inspector.stateFor(capabilities))
        }

        override fun onLost(network: Network) {
          emitIfChanged(inspector.currentState())
        }

        override fun onUnavailable() {
          emitIfChanged(NetworkStateMapper.DISCONNECTED)
        }
      }
      try {
        // API 24+. Tracks the system default network, the one apps use.
        cm.registerDefaultNetworkCallback(callback)
        networkCallback = callback
      } catch (e: RuntimeException) {
        // SecurityException or the per-app callback limit. Monitoring is a
        // best-effort feature; explicit getNetworkState calls still work.
        Log.w(TAG, "Unable to register network callback", e)
      }
    }
  }

  override fun stopMonitoring() {
    synchronized(monitorLock) {
      val callback = networkCallback ?: return
      networkCallback = null
      lastEmitted = null
      val cm = reactApplicationContext.getSystemService(Context.CONNECTIVITY_SERVICE)
        as? ConnectivityManager ?: return
      try {
        cm.unregisterNetworkCallback(callback)
      } catch (e: IllegalArgumentException) {
        // Already unregistered.
      }
    }
  }

  override fun invalidate() {
    stopMonitoring()
    super.invalidate()
  }

  private fun emitIfChanged(state: NetworkStateResult) {
    synchronized(monitorLock) {
      // Capability callbacks fire for signal-strength and bandwidth updates
      // too. Only forward changes in the values we expose.
      if (networkCallback == null || state == lastEmitted) return
      lastEmitted = state
    }
    try {
      emitOnNetworkStateChange(stateToMap(state))
    } catch (e: RuntimeException) {
      Log.w(TAG, "Unable to emit network state change", e)
    }
  }

  companion object {
    const val NAME = NativeNetworkDiagnosticsSpec.NAME
    private const val TAG = "NetworkDiagnostics"
    private const val MIN_TIMEOUT_MS = 500L
    private const val MAX_TIMEOUT_MS = 60_000L

    fun stateToMap(state: NetworkStateResult): WritableMap = Arguments.createMap().apply {
      putBoolean("connected", state.connected)
      putString("type", state.type)
      state.vpn?.let { putBoolean("vpn", it) }
      state.validated?.let { putBoolean("validated", it) }
      state.captivePortal?.let { putBoolean("captivePortal", it) }
      state.metered?.let { putBoolean("metered", it) }
      state.constrained?.let { putBoolean("constrained", it) }
    }

    fun outcomeToMap(outcome: ProbeOutcome): WritableMap = Arguments.createMap().apply {
      putBoolean("responded", outcome.responded)
      outcome.statusCode?.let { putInt("statusCode", it) }
      outcome.totalMs?.let { putDouble("totalMs", it) }
      outcome.dnsMs?.let { putDouble("dnsMs", it) }
      outcome.tcpConnectMs?.let { putDouble("tcpConnectMs", it) }
      outcome.tlsHandshakeMs?.let { putDouble("tlsHandshakeMs", it) }
      outcome.errorCode?.let { putString("errorCode", it) }
      outcome.errorMessage?.let { putString("errorMessage", it) }
    }
  }
}
